### PR TITLE
Implements maps, changes createFrom to constructor

### PR DESCRIPTION
**Pull request by urjitbhatia**
Fixes:
- https://github.com/tkrajina/typescriptify-golang-structs/issues/9
- https://github.com/tkrajina/typescriptify-golang-structs/issues/8
- https://github.com/tkrajina/typescriptify-golang-structs/issues/16

### CODE REVIEW

**Comment by tkrajina** [comment]
Hi @urjitbhatia and thanks for your pull request. I tested it now and I think there are a few small problems we need to fix before merging it.

But before explaining those, another suggestion for the future. Since you're fixing three distinct issues -- this should have been three different pull requests. That would allow me to merge one or two immediately and discuss/update the third one.

OK, and now for the "small problems". First of all the map thing, you don't have a test. I implemented my own to see what it produces:
```
type StructWithMap struct {
	SimpleMap  map[string]int    `json:"simple"`
	ComplexMap map[string]Person `json:"complex"`
}

func TestMap(t *testing.T) {
	converter := New()

	converter.Add(StructWithMap{})
	converter.ConstructorMethod = true
	converter.BackupDir = ""

	converted, err := converter.Convert(nil)
	if err != nil {
		t.FailNow()
	}
	fmt.Println(converted)
    // TODO: asserts...
}
```
It produces:
```
export class StructWithMap {
    simple: {[key: string]: number};
    complex: {[key: string]: Person};

    constructor(source: any) {
        if ('string' === typeof source) source = JSON.parse(source);
        this.simple = source["simple"] ? source["simple"] : null;
        this.complex = source["complex"] ? source["complex"] : null;
    }

}
```
But note that, in case of the `complex` -- it doesn't call the constructor of each key value. It just copies the values. If `complex` were an array it would create `source["complex"].map(function(element: any)` ... and make sure every element is converted properly.

**Comment by tkrajina** [comment]
OK, and the other issue is with constructors. Although I should probably have gone with constructors instead of `createFrom()`, by totally removing `createFrom()`  and `CreateFromMethod`/`ConstructorMethod` - we're also breaking the existing code for all who use this library/tool. 

My idea was to **add** `ConstructorMethod` and then update `createFrom()` from:
```
    static createFrom(source: any) {
        if ('string' === typeof source) source = JSON.parse(source);
        const result = new Test();
        result.field = source["field"];
        return result;
    }
```
to
```
    static createFrom(source: any, target = new Test()) {
        if ('string' === typeof source) source = JSON.parse(source);
        target.field = source["field"];
        return target;
    }
```
Then, the constructor would simply be:
```
constructor(source: any) {
    Test.createFrom(source, this);
}
```
By doing this -- all the existing code (including the Golang generating code and Typescript generated code) would keep working.

What do you think?

**Comment by urjitbhatia** [comment]
Thanks for the review - yeah it makes sense. I think I jumped the gun on opening the PR :) I made some more fixes after that and added tests too. I'll try to clean it up and open new PRs soon.

**Comment by shackra** [comment]
any news with this PR?

**Comment by tkrajina** [comment]
> any news with this PR?

@shackra I implemented the constructor in another branch (`no-or-null`) which I'm currently using and will probably merge in master sometimes. I'll try to add maps there before merging it to master.

**Pull request closed without merging**
